export const CLASSES_LIST = [
  "Creche",
  "Jardim de Infância",
  "1ªclasse",
  "2ªclasse",
  "3ªclasse",
  "4ªclasse",
  "5ªclasse",
  "6ªclasse",
  "7ªclasse",
  "8ªclasse",
  "9ªclasse",
  "10ªclasse",
  "11ªclasse",
  "12ªclasse",
  "Profissional 1º ano",
  "Profissional 2ºano",
  "Técnico 1º ano",
  "Técnico 2º ano",
  "Técnico 3º ano",
  "Bacharelato",
  "Licenciatura",
  "Pos-Graduação",
  "Mestrado",
  "Doutorado",
  "Pos-Doutoramento"
];

export const ESCOLAS_LIST = [
  "Anzú Mama - Água Grande (Pre Escolar)",
  "Associação de Jovens na Luta para o Futuro-A JOLF - Água Grande (Profissional)",
  "Associação I. Socio Educativa das Crianças - Água Grande (Pre Escolar)",
  "Bambino - Água Grande (Pre Escolar)",
  "BERÇÁRIO AMOR MATERNAL - Água Grande (Pre Escolar)",
  "BERÇÁRIO OS ANJINHOS - Água Grande (Pre Escolar)",
  "BERÇARIO TIA BELA - Água Grande (Pre Escolar)",
  "BERÇARIO TIA ELSA - Água Grande (Pre Escolar)",
  "Casa dos Tometinhos - Água Grande (Pre Escolar)",
  "Centro Agrónomo - CATAP - Mé-Zóchi (Profissional)",
  "Centro de Formação Profissional Sagrada Esperança Limitada - Água Grande (Profissional)",
  "Centro Formação Profissional O Golfinho - Água Grande (Profissional)",
  "Centro Infantil Bombom - Mé-Zóchi (Pre Escolar)",
  "Centro Politécnico - Água Grande (Profissional)",
  "Centro Profissional Brasil STP - Água Grande (Profissional)",
  "Centro Profissional Budo -Budo - Água Grande (Profissional)",
  "Centro Social de Formação Profissional de STP - Água Grande (Profissional)",
  "Centro World Link Solutions - Água Grande (Profissional)",
  "COLÉGIO ADVENTISTA-Cosme da Mota - Água Grande (Pre Escolar)",
  "Colégio Sto António - Água Grande (Pre Escolar)",
  "CRECHE CASA DAS ABELINHAS - Água Grande (Pre Escolar)",
  "Drealândia - Água Grande (Pre Escolar)",
  "Elsa Morera e Eugénio Frota Moreira - Água Grande (Pre Escolar)",
  "Escola Básica Secundária de Neves - Lembá (Ensino Basico)",
  "Escola Básica de Diogo Vaz - Lembá (Ensino Basico)",
  "Escola Básica 12 de Julho - Água Grande (Ensino Basico)",
  "Escola Básica 1º de Junho - Água Grande (Ensino Basico)",
  "Escola Básica Adão Deus Lima - Cantagalo (Ensino Basico)",
  "Escola Básica Agostinho Neto - Lobata (Ensino Basico)",
  "Escola Básica Anastácio Cupertino Batista de Sousa - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Atanásio Gomes - Água Grande (Ensino Basico)",
  "Escola Básica de Pantufo - Água Grande (Ensino Basico)",
  "Escola Básica de Abade - Principe (Ensino Basico)",
  "Escola Básica de Água das Belas - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Almas (2º Ciclo) - Mé-Zóchi (Ensino Basico)",
  "Em que escola estuda atualmente?",
  "Escola Básica de Angolares - Caué (Ensino Basico)",
  "Escola Básica de Angra Toldo - Caué (Ensino Basico)",
  "Escola Básica de Anselmo Andrade - Cantagalo (Ensino Basico)",
  "Escola Básica de Boa Entrada - Lobata (Ensino Basico)",
  "Escola Básica de Boa Morte - Água Grande (Ensino Basico)",
  "Escola Básica de Bôbo - Forro - Água Grande (Ensino Basico)",
  "Escola Básica de Caixão Grande - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Caldeiras - Lobata (Ensino Basico)",
  "Escola Básica de Chácara - Água Grande (Ensino Basico)",
  "Escola Básica de Claudino Faro - Cantagalo (Ensino Basico)",
  "Escola Básica de Colónia Açoreana - Cantagalo (Ensino Basico)",
  "Escola Básica de Conde - Lobata (Ensino Basico)",
  "Escola Básica de Diogo Simão - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Dona Augusta - Caué (Ensino Basico)",
  "Escola Básica de Esprainha - Lembá (Ensino Basico)",
  "Escola Básica de Folha-Féde - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Guadalupe (2º Ciclo) - Lobata (Ensino Basico)",
  "Escola Básica de Ilhéu das Rolas - Caué (Ensino Basico)",
  "Escola Básica de Iô Grande - Caué (Ensino Basico)",
  "Escola Básica de Java - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Lemos - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Magodinho - Lobata (Ensino Basico)",
  "Escola Básica de Mendes da Silva - Cantagalo (Ensino Basico)",
  "Escola Básica de Milagrosa - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Monte Café - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Monte Mário - Caué (Ensino Basico)",
  "Escola Básica de Neves (1º Ciclo) - Lembá (Ensino Basico)",
  "Escola Básica de Nova Estrela - Principe (Ensino Basico)",
  "Escola Básica de Oquê-del-Rei - Água Grande (Ensino Basico)",
  "Escola Básica de Otótó - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Padrão - Principe (Ensino Basico)",
  "Escola Básica de Pedroma - Cantagalo (Ensino Basico)",
  "Escola Básica de Ponta Figo - Lembá (Ensino Basico)",
  "Escola Básica de Porto Alegre (1º Ciclo) - Caué (Ensino Basico)",
  "Escola Básica de Porto Real - Principe (Ensino Basico)",
  "Escola Básica de Praia das Burras - Principe (Ensino Basico)",
  "Escola Básica de Praia das Conchas - Lobata (Ensino Basico)",
  "Escola Básica de Praia Gamboa - Água Grande (Ensino Basico)",
  "Escola Básica de Praia Inhame - Principe (Ensino Basico)",
  "Escola Básica de Praia Morro Peixe - Lobata (Ensino Basico)",
  "Escola Básica de Praia Rei - Cantagalo (Ensino Basico)",
  "Escola Básica de Quimpo - Cantagalo (Ensino Basico)",
  "Escola Básica de Ribeira Afonso - Cantagalo (Ensino Basico)",
  "Escola Básica de Ribeira Peixe - Caué (Ensino Basico)",
  "Escola Básica de Riboque Capital - Água Grande (Ensino Basico)",
  "Escola Básica de Riboque Santana - Cantagalo (Ensino Basico)",
  "Escola Básica de Rosema - Lembá (Ensino Basico)",
  "Escola Básica de Sam Fenícia - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de San Marçal - Água Grande (Ensino Basico)",
  "Escola Básica de Santa Catarina (1º Ciclo) - Lembá (Ensino Basico)",
  "Escola Básica de Santa Jeny - Lembá (Ensino Basico)",
  "Escola Básica de Santa Luzia - Lobata (Ensino Basico)",
  "Escola Básica de Santo António II - Principe (Ensino Basico)",
  "Escola Básica de São João - Água Grande (Ensino Basico)",
  "Escola Básica de São Joaquim - Principe (Ensino Basico)",
  "Escola Básica de Sundy - Principe (Ensino Basico)",
  "Escola Básica de Trindade - Mé-Zóchi (Ensino Basico)",
  "Escola Básica de Uba-Budo - Cantagalo (Ensino Basico)",
  "Escola Básica de Vila José - Caué (Ensino Basico)",
  "Escola Básica Domingos Daio (Côr de Rosa) - Lembá (Ensino Basico)",
  "Escola Básica Dona Maria de Jesus - Água Grande (Ensino Basico)",
  "Escola Básica Francisco Tenreiro - Água Grande (Ensino Basico)",
  "Escola Básica Internacional - Água Grande (Ensino Basico)",
  "Escola Básica Januário Graça - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Januário Graça-RAP - Principe (Ensino Basico)",
  "Escola Básica Jorge Batista de Sousa(Almeirim) - Água Grande (Ensino Basico)",
  "Escola Básica José Leal Bouças - Lobata (Ensino Basico)",
  "Escola Básica Lourenço Quaresma das Neves (POTÓ) - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Mãe Clara - Lembá (Ensino Basico)",
  "Escola Básica Manuel do Rosário (Almas 1º ciclo) - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Manuel Quaresma Bragança (Batepá) - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Maria Augusta da Silva de la Cruz Martinez - Cantagalo (Ensino Basico)",
  "Escola Básica Mário Moniz(Ribeira Funda) - Lembá (Ensino Basico)",
  "Escola Básica Nossa Senhora das Neves - Lembá (Ensino Basico)",
  "Escola Básica Patrice Lumumba - Água Grande (Ensino Basico)",
  "Escola Básica Paula Lavres - Principe (Ensino Basico)",
  "Escola Básica Secundária Albertina Matos - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Secundária António Francisco - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Secundária Centro Promoção Madalena de Canossa - Água Grande (Ensino Basico)",
  "Escola Básica Secundária de Algés - Cantagalo (Ensino Basico)",
  "Escola Básica Secundária de Angolares - Caué (Ensino Basico)",
  "Escola Básica Secundária de Desejada - Lobata (Ensino Basico)",
  "Escola Básica Secundária de Porto Alegre - Caué (Ensino Basico)",
  "Escola Básica Secundária de Ribeira Afonso - Cantagalo (Ensino Basico)",
  "Escola Básica Secundária de Santa Catarina (2º Ciclo) - Lembá (Ensino Basico)",
  "Escola Básica Secundária de Santana - Cantagalo (Ensino Basico)",
  "Escola Básica Secundária Januário José da Costa - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Secundária Liceu Nacional - Água Grande (Ensino Basico)",
  "Escola Básica Secundária Maria Manuela Margarido - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Secundária Portuguesa-CELP - Água Grande (Ensino Basico)",
  "Escola Básica Secundária Sebasteão dos Anjos do Rosário - Lobata (Ensino Basico)",
  "Escola Básica Trindade Sousa Pontes - Mé-Zóchi (Ensino Basico)",
  "Escola Básica Venâncio Pires - Lobata (Ensino Basico)",
  "Escola Integrada Fernanda Margato - Água Grande (Pre Escolar)",
  "Escola Profissional de Água Grande-EPAG - Água Grande (Profissional)",
  "Escola Profissional e Profissionalizante de STP(EPPAR) - Água Grande (Profissional)",
  "Escritório dos pequeninos - Água Grande (Pre Escolar)",
  "Externato Makucu - Água Grande (Pre Escolar)",
  "EXTERNATO PRINCEZINHA - Água Grande (Pre Escolar)",
  "Faculdade de Ciências e Tecnologia (FCT) - Água Grande (Superior)",
  "Info@lte-Informatica e Designer limitada - Água Grande (Profissional)",
  "Instituição Particular de Solidariedade Social Portuguesa-IPSS - Água Grande (Profissional)",
  "Instituto Profissional de Gestão e Negócio -FORVAT -GROP - Água Grande (Profissional)",
  "Instituto S- E-de Mulundo-ARCAR - Água Grande (Pre Escolar)",
  "Instituto Superior de Ciências de Saúde Victor Sá Machado (ISCSVSM) - Água Grande (Superior)",
  "Instituto Superior de Educação e Comunicação (ISEC) - Água Grande (Superior)",
  "Instituto Universitário de Contabilidade e Informática (IUCAI) - Água Grande (Profissional)",
  "Jardim Baú dos Sonhos - Mé-Zóchi (Pre Escolar)",
  "Jardim 1º de Maio - Água Grande (Pre Escolar)",
  "Jardim Agostinho Neto - Lobata (Pre Escolar)",
  "Jardim Alda do Espiríto Santo - Principe (Pre Escolar)",
  "Jardim Alda Graça - Água Grande (Pre Escolar)",
  "Jardim Arca de Noé - Lembá (Pre Escolar)",
  "JARDIM ARCO-IRIS - Água Grande (Pre Escolar)",
  "Jardim criança é Vida /JOCUM - Mé-Zóchi (Pre Escolar)",
  "Jardim de Abade - Principe (Pre Escolar)",
  "Jardim de Agripalma - Caué (Pre Escolar)",
  "Jardim de Água Casada - Lobata (Pre Escolar)",
  "Jardim de Agua Izé - Cantagalo (Pre Escolar)",
  "Jardim de Água Porca - Água Grande (Pre Escolar)",
  "Jardim de Alto Douro - Cantagalo (Pre Escolar)",
  "Jardim de Angolares - Caué (Pre Escolar)",
  "Jardim de Anselmo Andrade - Cantagalo (Pre Escolar)",
  "Jardim de Arribana - Lembá (Pre Escolar)",
  "Jardim de Bela Vista - Lobata (Pre Escolar)",
  "Jardim de Belo Monte - Principe (Pre Escolar)",
  "Jardim de Bem Posta - Mé-Zóchi (Pre Escolar)",
  "Jardim de Bernado Faro - Cantagalo (Pre Escolar)",
  "Jardim de Boa Entrada - Lobata (Pre Escolar)",
  "Jardim de Bombom - Mé-Zóchi (Pre Escolar)",
  "Jardim de Caldeiras - Lobata (Pre Escolar)",
  "Jardim de Canavial - Lobata (Pre Escolar)",
  "Jardim de Caridade - Cantagalo (Pre Escolar)",
  "Jardim de CATAP - Mé-Zóchi (Pre Escolar)",
  "Jardim de Claudino Faro - Cantagalo (Pre Escolar)",
  "Jardim de Colónia AçorIana - Cantagalo (Pre Escolar)",
  "Jardim de Diogo Vaz - Lembá (Pre Escolar)",
  "Jardim de Dona Augusta - Caué (Pre Escolar)",
  "Jardim de Esprainha - Lembá (Pre Escolar)",
  "Jardim de Fernão Dias - Lobata (Pre Escolar)",
  "Jardim de Ferreira Governo - Lobata (Pre Escolar)",
  "Jardim de Generosa - Lembá (Pre Escolar)",
  "Jardim de Infância da Madalena - Água Grande (Pre Escolar)",
  "Jardim de Java - Mé-Zóchi (Pre Escolar)",
  "Jardim de Lar de Luz - Mé-Zóchi (Pre Escolar)",
  "Jardim de Laranjeira - Lobata (Pre Escolar)",
  "Jardim de Lembá - Lembá (Pre Escolar)",
  "Jardim de Maianço - Lobata (Pre Escolar)",
  "Jardim de Malanza - Caué (Pre Escolar)",
  "Jardim de Margão - Mé-Zóchi (Pre Escolar)",
  "Jardim de Mato Cana - Cantagalo (Pre Escolar)",
  "Jardim de Micoló - Lobata (Pre Escolar)",
  "Jardim de Milagrosa - Mé-Zóchi (Pre Escolar)",
  "Jardim de Monte Café - Mé-Zóchi (Pre Escolar)",
  "Jardim de Monte Forte - Lembá (Pre Escolar)",
  "Jardim de Monte Macaco - Mé-Zóchi (Pre Escolar)",
  "Jardim de Morro Peixe - Lobata (Pre Escolar)",
  "Jardim de Mulundo - Lembá (Pre Escolar)",
  "Jardim de Nova Esperança - Lembá (Pre Escolar)",
  "Jardim de Nova Olinda - Cantagalo (Pre Escolar)",
  "Jardim de Novo Destino - Mé-Zóchi (Pre Escolar)",
  "Jardim de Obô Rosema - Lembá (Pre Escolar)",
  "Jardim de Pedroma - Cantagalo (Pre Escolar)",
  "Jardim de Pinheira - Cantagalo (Pre Escolar)",
  "Jardim de Plancas I - Lobata (Pre Escolar)",
  "Jardim de Ponta do Sol - Principe (Pre Escolar)",
  "Jardim de Ponta Figo - Lembá (Pre Escolar)",
  "Jardim de Porto Alegre - Caué (Pre Escolar)",
  "Jardim de Porto Real - Principe (Pre Escolar)",
  "Jardim de Praia das Burras - Principe (Pre Escolar)",
  "Jardim de Praia das Conchas Roça - Lobata (Pre Escolar)",
  "Jardim de Quimpo - Cantagalo (Pre Escolar)",
  "Jardim de Quinta das Palmeiras - Mé-Zóchi (Pre Escolar)",
  "Jardim de Ribeira Peixe - Caué (Pre Escolar)",
  "Jardim de San Marçal - Água Grande (Pre Escolar)",
  "Jardim de Santa Clotilde - Cantagalo (Pre Escolar)",
  "Jardim de Santa Clotilde - Lembá (Pre Escolar)",
  "Jardim de Santa Luzia - Lobata (Pre Escolar)",
  "Jardim de Santa Margarida - Mé-Zóchi (Pre Escolar)",
  "Jardim de Santana - Cantagalo (Pre Escolar)",
  "Jardim de Santarém - Lobata (Pre Escolar)",
  "Jardim de Santo António II - Principe (Pre Escolar)",
  "Jardim de Santo António - Água Grande (Pre Escolar)",
  "Jardim de São Joaquim - Principe (Pre Escolar)",
  "Jardim de São José - Lembá (Pre Escolar)",
  "Jardim de São José - Mé-Zóchi (Pre Escolar)",
  "Jardim de São Nicolau - Mé-Zóchi (Pre Escolar)",
  "Jardim de Saudade - Mé-Zóchi (Pre Escolar)",
  "Jardim de Sundy - Principe (Pre Escolar)",
  "Jardim de Tchada - Principe (Pre Escolar)",
  "Jardim de Terreiro velho - Principe (Pre Escolar)",
  "Jardim de Uba - Budo - Cantagalo (Pre Escolar)",
  "Jardim de Vigoço - Água Grande (Pre Escolar)",
  "Jardim de Vista Alegre - Mé-Zóchi (Pre Escolar)",
  "Jardim dos Sonhos - Água Grande (Pre Escolar)",
  "Jardim Ester Will - Mé-Zóchi (Pre Escolar)",
  "Jardim Inocência - Principe (Pre Escolar)",
  "Jardim João Paulo Cassandra - Principe (Pre Escolar)",
  "Jardim Lar São José - Principe (Pre Escolar)",
  "Jardim Madres Canossianas - Água Grande (Pre Escolar)",
  "Jardim Mina Anzu - Água Grande (Pre Escolar)",
  "Jardim Mino Quetê - Principe (Pre Escolar)",
  "Jardim Ninho de Alegria - Água Grande (Pre Escolar)",
  "Jardim Nova Canaâ - Cantagalo (Pre Escolar)",
  "Jardim Olof-Palme - Mé-Zóchi (Pre Escolar)",
  "JARDIM ONG. AMIGOS DA SARA - Água Grande (Pre Escolar)",
  "Jardim Os Inhamisinhos - Principe (Pre Escolar)",
  "Jardim Padre Manuel Cristóvão - Cantagalo (Pre Escolar)",
  "Jardim Páscoa Carvalho - Água Grande (Pre Escolar)",
  "Jardim Pêpê (Boa Semente) - Mé-Zóchi (Pre Escolar)",
  "Jardim Pêpê (Sementinha) - Cantagalo (Pre Escolar)",
  "Jardim Pimpolho - Lembá (Pre Escolar)",
  "Jardim Pincaté - Principe (Pre Escolar)",
  "Jardim Pôr do Sol - Lembá (Pre Escolar)",
  "Jardim Porcelana - Água Grande (Pre Escolar)",
  "Jardim Princesa Maribel - Mé-Zóchi (Pre Escolar)",
  "Jardim Sam Quilembê - Lobata (Pre Escolar)",
  "Jardim SantaTeresinha - Principe (Pre Escolar)",
  "Jardim Santo Isidoro - Cantagalo (Pre Escolar)",
  "Jardim Sol Sem Fronteira - Cantagalo (Pre Escolar)",
  "Jardim Tartaruga - Água Grande (Pre Escolar)",
  "JARDIM TIA LUISA - Água Grande (Pre Escolar)",
  "Limoeiros - Água Grande (Pre Escolar)",
  "Mimos e Alegria - Água Grande (Pre Escolar)",
  "Nascente dos pequeninos - Água Grande (Pre Escolar)",
  "Núcleo do Sistémico, Neis-Medicina - Água Grande (Pre Escolar)",
  "Nurseny/Primary Father's CourtInt Scool - Água Grande (Pre Escolar)",
  "OFICINA DE SONHO - Água Grande (Pre Escolar)",
  "Os Miminhos - Água Grande (Pre Escolar)",
  "Pepe (Deçu Sá Buá) - Água Grande (Pre Escolar)",
  "Programa educativo pré-Escolar (PEPE) - Água Grande (Pre Escolar)",
  "Saidos da Casca - Água Grande (Pre Escolar)",
  "SERCOM - Água Grande (Profissional)",
  "Universidade Évora - Água Grande (Superior)",
  "Universidade Lusíada-Fundação Atenas - Água Grande (Superior)",
  "Visão Associação para a Promoção Educativa e Socio Cultural (ONG-NACIONAL) - Água Grande (Pre Escolar)"
];
