name: Build and Deploy Frontend to Production on Tag Creation
on:
  push:
    tags:
      - 'prod-frontend-v*'

jobs:
  publish-docker-prod-image:
    runs-on: ubuntu-latest
    outputs:
      fe_tag: ${{ steps.extract_tag.outputs.fe_tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "fe_tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the Kenon Frontend Docker image
        run: |
          LABEL=${GITHUB_REF_NAME}  # Usando o nome da tag extraída
          echo "Building Docker image for ${LABEL}..."
          docker build . --tag ghcr.io/stssocialst-stp/kenon-frontend:${LABEL}

      - name: Push Docker image to GHCR
        run: |
          LABEL=${GITHUB_REF_NAME}
          echo "Pushing Docker image for ${LABEL}..."
          docker push ghcr.io/stssocialst-stp/kenon-frontend:${LABEL}

  deploy-frontend-prod:
    runs-on: coremis-prod
    needs: publish-docker-prod-image
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      DOMAIN: ${{ vars.DOMAIN }}
      HTTP_PORT: ${{ vars.HTTP_CLIENT_PORT }}
      HTTPS_PORT: ${{ vars.HTTPS_CLIENT_PORT }}
      GATEWAY_PORT_S: ${{ vars.GATEWAY_PORT_S }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }} 
      DB_USER: ${{ vars.DB_USER }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_ENGINE: ${{ vars.DB_ENGINE }}
      SITE_ROOT: ${{ vars.SITE_ROOT }}
      DB_TAG: ${{ vars.DB_TAG }}
      BE_TAG: ${{ vars.BE_TAG }}
      
      # Passando a tag do frontend do primeiro job
      FE_TAG: ${{ needs.publish-docker-prod-image.outputs.fe_tag }}

      OPENIMIS_FE_CONF_JSON: ${{ vars.OPENIMIS_FE_CONF_JSON }}
      CSRF_TRUSTED_ORIGINS: ${{ vars.CSRF_TRUSTED_ORIGINS }}
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
      DJANGO_LOG_LEVEL: ${{ vars.DJANGO_LOG_LEVEL }}
      DJANGO_LOG_HANDLER: ${{ vars.DJANGO_LOG_HANDLER }}
      DJANGO_MIGRATE: ${{ vars.DJANGO_MIGRATE }}
      EMAIL_HOST: ${{ vars.EMAIL_HOST }}
      EMAIL_PORT: ${{ vars.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}
      EMAIL_USE_TLS: ${{ vars.EMAIL_USE_TLS }}
      OPENSEARCH_ADMIN: ${{ vars.OPENSEARCH_ADMIN }}
      OPENSEARCH_PASSWORD: ${{ vars.OPENSEARCH_PASSWORD }}
      OPENSEARCH_BASIC_TOKEN: ${{ vars.OPENSEARCH_BASIC_TOKEN }}
      OPENSEARCH_HOST: ${{ vars.OPENSEARCH_HOST }}
      CELERY_BROKER_URL: ${{ vars.CELERY_BROKER_URL }}
      DATA_UPLOAD_MAX_MEMORY_SIZE: ${{ vars.DATA_UPLOAD_MAX_MEMORY_SIZE }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Create .env file from workflow env
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/.env
            PROJECT_NAME=${PROJECT_NAME}
            DOMAIN=${DOMAIN}
            HTTP_PORT=${HTTP_PORT}
            HTTPS_PORT=${HTTPS_PORT}
            GATEWAY_PORT_S=${GATEWAY_PORT_S}
            DB_PASSWORD=${DB_PASSWORD}
            DB_USER=${DB_USER}
            DB_NAME=${DB_NAME}
            DB_HOST=${DB_HOST}
            DB_PORT=${DB_PORT}
            DB_ENGINE=${DB_ENGINE}
            SITE_ROOT=${SITE_ROOT}
            DB_TAG=${DB_TAG}
            BE_TAG=${BE_TAG}
            FE_TAG=${FE_TAG}  # A tag do frontend aqui
            OPENIMIS_FE_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
            CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            REACT_APP_API_URL=${REACT_APP_API_URL}
            DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
            DJANGO_LOG_HANDLER=${DJANGO_LOG_HANDLER}
            DJANGO_MIGRATE=${DJANGO_MIGRATE}
            EMAIL_HOST=${EMAIL_HOST}
            EMAIL_PORT=${EMAIL_PORT}
            EMAIL_HOST_USER=${EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            EMAIL_USE_TLS=${EMAIL_USE_TLS}
            OPENSEARCH_ADMIN=${OPENSEARCH_ADMIN}
            OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
            OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN}
            OPENSEARCH_HOST=${OPENSEARCH_HOST}
            CELERY_BROKER_URL=${CELERY_BROKER_URL}
            DATA_UPLOAD_MAX_MEMORY_SIZE=${DATA_UPLOAD_MAX_MEMORY_SIZE}
          EOF

      - name: Remove old frontend container if exists
        run: |
          if [ "$(docker ps -a -q -f name=${PROJECT_NAME}-frontend)" ]; then
            echo "Removing old frontend container..."
            docker rm -f ${PROJECT_NAME}-frontend
          else
            echo "No old frontend container found."
          fi

      - name: Deploy frontend (pull image and run container)
        run: |
          cd $GITHUB_WORKSPACE
          echo "Deploying frontend with FE_TAG=${FE_TAG}"
          docker pull ghcr.io/stssocialst-stp/kenon-frontend:${FE_TAG}
          docker run -d \
            --name ${PROJECT_NAME}-frontend \
            --restart always \
            --env-file .env \
            -e REACT_APP_API_URL=api \
            -e NEW_OPENIMIS_HOST=${DOMAIN} \
            -e OPENIMIS_CONF_JSON="${OPENIMIS_FE_CONF_JSON}" \
            -e OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN} \
            -p ${HTTP_PORT:-4005}:80 \
            -p ${HTTPS_PORT:-4006}:443 \
            -v ./data/certbot/conf:/etc/letsencrypt \
            -v ./data/certbot/www:/var/www/certbot \
            -v ../../conf/ngnix:/conf/ \
            --network kenon-stp-net \
            ghcr.io/stssocialst-stp/kenon-frontend:${FE_TAG}
